query FeaturedProduct {
  product(where: { featured: { _eq: true } }) {
    id
    image {
      alt
      height
      id
      size
      src
      width
    }
    description
    name
    recommendeds {
      productByRecommendedProductId {
        id
        name
        image {
          alt
          height
          id
          size
          src
          width
        }
      }
    }
  }
}
