query products(
  $offset: Int = 0
  $limit: Int = 2
  $categories: [String!] = ["dogs", "nature"]
  $gte: numeric = 0
  $lte: numeric = 1000000
) {
  products(
    limit: $limit
    offset: $offset
    where: {
      category: { slug: { _in: $categories } }
      price: { _gte: $gte, _lte: $lte }
      featured: { _eq: false }
    }
  ) {
    nodes {
      id
      name
      price
      bestseller
      description
      image {
        alt
        height
        id
        size
        src
        width
      }
      category {
        id
        name
        slug
      }
    }
  }
  productsCount: products(
    where: {
      category: { slug: { _in: $categories } }
      price: { _gte: $gte, _lte: $lte }
      featured: { _eq: false }
    }
  ) {
    aggregate {
      count
    }
  }
}
