fragment product on product {
  bestseller
  category_id
  currency
  description
  featured
  id
  image {
    alt
    height
    id
    size
    src
    width
  }
  name
  price
}

query ProductsQuery {
  products {
    nodes {
      ...product
    }
  }
  featuredProduct: product(where: { featured: { _eq: true } }) {
    ...product
    recommendeds {
      productByRecommendedProductId {
        id
        name
        image {
          alt
          height
          id
          size
          src
          width
        }
      }
    }
  }
}
