fragment product on product {
  id
  name
  price
  bestseller
  description
  image {
    alt
    height
    id
    size
    src
    width
  }
  category {
    id
    name
  }
}

query ProductsQuery($offset: Int = 0, $limit: Int = 6) {
  products(limit: $limit, offset: $offset) {
    nodes {
      ...product
    }
    aggregate {
      count
    }
  }
  featuredProduct: product(where: { featured: { _eq: true } }, limit: 1) {
    ...product
    recommendeds {
      productByRecommendedProductId {
        id
        name
        image {
          alt
          height
          id
          size
          src
          width
        }
      }
    }
  }
}
